name: dockerhub-publish

on:
  push:
    branches: ["main"]
    tags: ["v*.*.*"]

env:
  IMAGE_NAME: guoyk/minit

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: dockerhub login
        uses: docker/login-action@v2
        with:
          username: guoyk
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: dockerhub meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }}

      - name: dockerhub build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
